// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBinanceSymbolInfo(arg1) {
  return window['go']['main']['App']['GetBinanceSymbolInfo'](arg1);
}

export function GetBinanceSymbols() {
  return window['go']['main']['App']['GetBinanceSymbols']();
}

export function GetBinanceSymbolsByBaseAsset(arg1) {
  return window['go']['main']['App']['GetBinanceSymbolsByBaseAsset'](arg1);
}

export function GetBinanceSymbolsByQuoteAsset(arg1) {
  return window['go']['main']['App']['GetBinanceSymbolsByQuoteAsset'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
