// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBinanceSymbolInfo(arg1:string):Promise<main.SymbolInfo>;

export function GetBinanceSymbols():Promise<Array<main.SymbolInfo>>;

export function GetBinanceSymbolsByBaseAsset(arg1:string):Promise<Array<main.SymbolInfo>>;

export function GetBinanceSymbolsByQuoteAsset(arg1:string):Promise<Array<main.SymbolInfo>>;

export function Greet(arg1:string):Promise<string>;
